ALTER TABLE sale ADD COLUMN client_id UUID REFERENCES client(id);
ALTER TABLE sale ADD COLUMN fidelity_discount_applied NUMERIC(19, 2) NOT NULL DEFAULT 0.00;
ALTER TABLE sale ADD COLUMN points_earned INTEGER NOT NULL DEFAULT 0;
