ALTER TABLE fidelity_policy ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE fidelity_policy ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE fidelity_policy ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE fidelity ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE fidelity ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE fidelity ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
