spring:
  application:
    name: kalles-sale

  datasource:
    url: jdbc:postgresql://localhost:5432/kalles
    username: kalles_admin
    password: kalles_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  flyway:
    enabled: true
    locations: classpath:db/migration
